---
- name: Add Nginx repo
  apt_repository:
    repo: ppa:ondrej/nginx

- name: Install Nginx
  apt:
    name: nginx
    state: present
    force: yes
    update_cache: yes

- name: Check Nginx configs exist
  stat: path=/etc/nginx/.git
  register: git_exists

- name: Remove default Nginx configs
  file:
    path: /etc/nginx
    state: absent
  when: not git_exists.stat.exists

- name: Clone Nginx configs
  git:
    repo: https://github.com/spinupwp/wordpress-nginx
    dest: /etc/nginx
    version: master
    force: yes
  when: not git_exists.stat.exists

- name: Symlink default site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: reload nginx


  notify: restart nginx
